  version: '3.8'

services:
  backend:
    build: .
    container_name: backend_container
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
